[mgr]
prepend_keymap = [
  { on = [
    "<A-q>",
  ], run = 'escape', desc = "Escape visual mode, clear selected, cancel filter/search" },
  { on = [
    "k",
  ], run = 'arrow +1', desc = "Move a line down" },
  { on = [
    "l",
  ], run = 'arrow -1', desc = "Move a line up" },
  { on = [
    "j",
  ], run = 'leave', desc = "Go to parent directory" },
  { on = [
    ";",
  ], run = 'plugin smart-enter', desc = "Enter the child directory, or open the file" },
  { on = [
    "<S-k>",
  ], run = 'arrow +50%', desc = "Move half a page down" },
  { on = [
    "<S-l>",
  ], run = 'arrow -50%', desc = "Move half a page up" },
  { on = [
    "<A-k>",
  ], run = 'seek 3', desc = "Scroll preview" },
  { on = [
    "<A-l>",
  ], run = 'seek -3', desc = "Scroll preview" },
  { on = [
    "i",
  ], run = 'spot', desc = "Spot" },
  { on = [
    "f",
  ], run = "plugin jump-to-char", desc = "Jump to char" },
  { on = "l", run = "plugin smart-enter", desc = "Enter the child directory, or open the file" },
  { on = "F", run = "plugin smart-filter", desc = "Smart filter" },
  { on = "!", for = "unix", run = 'shell "$SHELL" --block', desc = "Open $SHELL here" },
]

[spot]
prepend_keymap = [
  { on = [
    "k",
  ], run = 'arrow +1', desc = "Move a line down" },
  { on = [
    "l",
  ], run = 'arrow -1', desc = "Move a line up" },
  { on = [
    "q",
  ], run = 'close', desc = "Close spotter" },
]
