# vim:fileencoding=utf-8:foldmethod=marker

# : Manager {{{

[mgr]
cwd = { fg = "#7dcfff" }

# TODO: remove
# Hovered
hovered = { reversed = true }
preview_hovered = { underline = true }

# Find
find_keyword = { fg = "#e0af68", bold = true, italic = true, underline = true }
find_position = { fg = "#f7768e", bg = "reset", bold = true, italic = true }

# Marker
marker_copied = { fg = "#9ece6a", bg = "#9ece6a" }
marker_cut = { fg = "#f7768e", bg = "#f7768e" }
marker_marked = { fg = "#7dcfff", bg = "#7dcfff" }
marker_selected = { fg = "#e0af68", bg = "#e0af68" }

# Count
count_copied = { fg = "#15161e", bg = "#9ece6a" }
count_cut = { fg = "#15161e", bg = "#f7768e" }
count_selected = { fg = "#15161e", bg = "#e0af68" }

# Border
border_symbol = "│"
border_style = { fg = "#414868" }

# : }}}


# : Tabs {{{

[tabs]
active = { fg = "#15161e", bg = "#7aa2f7", bold = true }
inactive = { fg = "#7aa2f7", bg = "#414868" }

# : }}}


# : Mode {{{

[mode]

normal_main = { fg = "#15161e", bg = "#7aa2f7", bold = true }
normal_alt = { fg = "#7aa2f7", bg = "#414868" }

# Select mode
select_main = { fg = "#15161e", bg = "#bb9af7", bold = true }
select_alt = { fg = "#bb9af7", bg = "#414868" }

# Unset mode
unset_main = { fg = "#15161e", bg = "#ffb86c", bold = true }
unset_alt = { fg = "#ffb86c", bg = "#414868" }

# : }}}


# : Status bar {{{

[status]
# Permissions
perm_sep = { fg = "#414868" }
perm_type = { fg = "#7aa2f7" }
perm_read = { fg = "#e0af68" }
perm_write = { fg = "#f7768e" }
perm_exec = { fg = "#9ece6a" }

# Progress
progress_label = { fg = "#c0caf5", bold = true }
progress_normal = { fg = "#9ece6a", bg = "#63667d" }
progress_error = { fg = "#e0af68", bg = "#f7768e" }

# : }}}


# : Pick {{{

[pick]
border = { fg = "#7aa2f7" }
active = { fg = "#f7768e", bold = true }
inactive = {}

# : }}}


# : Input {{{

[input]
border = { fg = "#7aa2f7" }
title = {}
value = {}
selected = { reversed = true }

# : }}}


# : Completion {{{

[cmp]
border = { fg = "#7aa2f7" }

# : }}}


# : Tasks {{{

[tasks]
border = { fg = "#7aa2f7" }
title = {}
hovered = { fg = "#f7768e", bold = true }

# : }}}


# : Which {{{

[which]
mask = { bg = "#414868" }
cand = { fg = "#7dcfff" }
rest = { fg = "#8998c9" }
desc = { fg = "#f7768e" }
separator = "  "
separator_style = { fg = "#83869c" }

# : }}}


# : Help {{{

[help]
on = { fg = "#7dcfff" }
run = { fg = "#f7768e" }
hovered = { reversed = true, bold = true }
footer = { fg = "#414868", bg = "#c0caf5" }

# : }}}


# : Spotter {{{

[spot]
border = { fg = "#7aa2f7" }
title = { fg = "#7aa2f7" }
tbl_col = { fg = "#7dcfff" }
tbl_cell = { fg = "#f7768e", bg = "#63667d" }

# : }}}


# : Notification {{{

[notify]
title_info = { fg = "#9ece6a" }
title_warn = { fg = "#e0af68" }
title_error = { fg = "#f7768e" }

# : }}}


# : File-specific styles {{{

[filetype]

rules = [
  # Image
  { mime = "image/*", fg = "#7dcfff" },
  # Media
  { mime = "{audio,video}/*", fg = "#e0af68" },
  # Archive
  { mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", fg = "#f7768e" },
  # Document
  { mime = "application/{pdf,doc,rtf}", fg = "#9ece6a" },
  # Virtual file system
  { mime = "vfs/{absent,stale}", fg = "#8998c9" },
  # Fallback
  { url = "*", fg = "#c0caf5" },
  { url = "*/", fg = "#7aa2f7" },
  # TODO: remove
  { name = "*", fg = "#c0caf5" },
  { name = "*/", fg = "#7aa2f7" },
]

# : }}}
